name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Run go vet
        run: go vet ./...

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
